Allow parsing exotic python version (#4949)
* python version: allow to parse exotic python version

On specific linux disto, the python version output can be exotic.

For example, in my machine I got the following:
```
❯ python --version
Python 3.11.3+chromium.29
```

Which can lead to not desired end of program:

```
from cryptography.hazmat.bindings._rust import openssl as rust_openssl
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: "Python version string has too many parts"
```

* python version: use splitn instead of split

* add test to check if the suffix is properly capture
* add newsfragment "fixed" entry for the changelog